# Default skill icon if none is set in skill config
default_skill_icon: player_head

# Number of rows to show in the skill inventory
skill_inventory_max_rows: 6

# The NBT key used to identify skill items.
# You generally should not need to change this.
nbt_key: "heroesskill"

# This is here in case you are switching out Magic for HeroesHotbar
# When you make the switch, any existing skill items will no longer work
# This makes sure that they disappear when dropped.
legacy_nbt_key: "skill"

# Default disabled icon url. Set to "" to turn off disabled icons, or override on a per-skill basis.
disabled_icon_url: http://textures.minecraft.net/texture/1c28376acb23cd93322c0a5d569b48b7cd631a6d65dd4f226adb9e9dd7e5c

# How often to scan each player's hotbar to update countdown timers
# This value is in ticks, so 20 would be once per second. Default is once per half second.
# Set to 0 to disable the cooldown timers.
update_interval: 10

# In-game text

skills:
    inventory_title_heroes: "$class Skills ($page/$pages)"
    inventory_title_heroes_secondary: "$class-$class2 Skills ($page/$pages)"
    item_name: "&6$skill"
    item_name_unavailable: "&c$skill"
    item_name_unprepared: "&e$skill"
    item_description: "$description"
    passive_description: "&1PASSIVE"
    none: "You have no skills!"
    none_on_page: "There are no skills on page $page"
    level_description: "&6Level $level"
    costs_description: "&eConsumes $description"
    description: "&a&o$description"
    description_extra: "&2&o$description"
    prepared_lore: "&3Memorize cost: &b$points"
    unlearned: "&cThe $skill skill must be learned before using!"
    prepare_limit: "&cYou cannot prepare any more skills, right-click a skill to unprepare it"
    prepared: "&bYou prepared &3$skill, &e$points &bpoints and &e$slots &bslots remaining"
    unprepared: "&2You unprepared &3$skill, &e$points &2points and &e$slots &2slots available"
    unprepare_lore: "&bRight-click or drop to unprepare"

cooldown:
    wait_seconds: another $seconds seconds
    wait_minutes: another $minutes minutes
    wait_hours: another $hours hours
    wait_moment: a moment
    wait_second: a second
    wait_minute: a minute
    wait_hour: another hour
    description_seconds: $seconds seconds
    description_minutes: $minutes minutes
    description_hours: $hours hours
    description_minute: One minute
    description_hour: One hour
    description_second: One second
    description_moment: A Moment
    description: "&eCooldown: &6$time"

costs:
    heroes_mana: "&6$amount &eMana"
    heroes_stamina: "&6$amount &eStamina"

